const APP_NAME = "kidsSportAdmin";

// AUTH
export const SET_AUTH_CREDENTIALS = `${APP_NAME}/SET_AUTH_CREDENTIALS`;
export const SET_AUTH_TOKENS = `${APP_NAME}/SET_AUTH_TOKENS`;
export const REFRESH_ACCESS_TOKEN = `${APP_NAME}/REFRESH_ACCESS_TOKEN`;

export const CHANGE_LANGUAGE = `${APP_NAME}/CHANGE_LANGUAGE`;

export const CLEAR_ON_SIGNOUT = `${APP_NAME}/CLEAR_ON_SIGNOUT`;
